const locations = [
'Detroit, Michigan',
'Chicago, Illinois',
'Los Angeles, California',
'New York City',
'Houston, Texas',
'Phoenix, Arizona',
'Philadelphia, Pennsylvania',
'San Antonio, Texas',
'San Diego, California',
'Dallas, Texas',
'San Jose, California',
'Austin, Texas',
'Jacksonville, Florida',
'Fort Worth, Texas',
'Columbus, Ohio',
'Indianapolis, Indiana',
'Charlotte, North Carolina',
'San Francisco, California',
'Seattle, Washington',
'Denver, Colorado',
'Nashville, Tennessee',
'Oklahoma City, Oklahoma',
'El Paso, Texas',
'Boston, Massachusetts',
'Portland, Oregon',
'Las Vegas, Nevada',
'Memphis, Tennessee',
'Louisville, Kentucky',
'Baltimore, Maryland',
'Milwaukee, Wisconsin',
'Albuquerque, New Mexico',
'Tucson, Arizona',
'Fresno, California',
'Sacramento, California',
'Kansas City, Missouri',
'Mesa, Arizona',
'Atlanta, Georgia',
'Omaha, Nebraska',
'Colorado Springs, Colorado',
'Raleigh, North Carolina',
'Long Beach, California',
'Virginia Beach, Virginia',
'Miami, Florida',
'Oakland, California',
'Minneapolis, Minnesota',
'Tulsa, Oklahoma',
'Bakersfield, California',
'Wichita, Kansas',
'Arlington, Texas',
'Aurora, Colorado',
'Tampa, Florida',
'New Orleans, Louisiana',
'Cleveland, Ohio',
'Honolulu, Hawaii',
'Anaheim, California',
'Lexington, Kentucky',
'Stockton, California',
'Corpus Christi, Texas',
'Henderson, Nevada',
'Riverside, California',
'Newark, New Jersey',
'St. Paul, Minnesota',
'Santa Ana, California',
'Cincinnati, Ohio',
'Irvine, California',
'Orlando, Florida',
'Pittsburgh, Pennsylvania',
'St. Louis, Missouri',
'Greensboro, North Carolina',
'Jersey City, New Jersey',
'Anchorage, Alaska',
'Lincoln, Nebraska',
'Plano, Texas',
'Durham, North Carolina',
'Buffalo, New York',
'Chandler, Arizona',
'Chula Vista, California',
'Toledo, Ohio',
'Madison, Wisconsin',
'Gilbert, Arizona',
'Reno, Nevada',
'Fort Wayne, Indiana',
'North Las Vegas, Nevada',
'St. Petersburg, Florida',
'Lubbock, Texas',
'Irving, Texas',
'Laredo, Texas',
'Winston-Salem, North Carolina',
'Chesapeake, Virginia',
'Glendale, Arizona',
'Garland, Texas',
'Scottsdale, Arizona',
'Norfolk, Virginia',
'Boise, Idaho',
'Fremont, California',
'Spokane, Washington',
'Santa Clarita, California',
'Baton Rouge, Louisiana',
'Richmond, Virginia',
'Hialeah, Florida'
];
export { locations };
